require("config.options")
require("config.keybinds")
require("config.autocmds")
require("config.commands")
require("config.pack")

require("plugins.colors")
require("plugins.treesitter")
require("plugins.lsp")
require("plugins.harpoon")
require("plugins.lualine")
require("plugins.noice")
require("plugins.fugitive")
require("plugins.conform")
require("plugins.highlight")
